// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// interpolateAkimaGrid
void interpolateAkimaGrid(NumericVector x, NumericVector y, NumericMatrix grid, NumericMatrix output);
RcppExport SEXP _ProFound_interpolateAkimaGrid(SEXP xSEXP, SEXP ySEXP, SEXP gridSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output(outputSEXP);
    interpolateAkimaGrid(x, y, grid, output);
    return R_NilValue;
END_RCPP
}
// interpolateLinearGrid
void interpolateLinearGrid(NumericVector xseq, NumericVector yseq, NumericMatrix tempmat_sky, NumericMatrix output);
RcppExport SEXP _ProFound_interpolateLinearGrid(SEXP xseqSEXP, SEXP yseqSEXP, SEXP tempmat_skySEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xseq(xseqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yseq(yseqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tempmat_sky(tempmat_skySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output(outputSEXP);
    interpolateLinearGrid(xseq, yseq, tempmat_sky, output);
    return R_NilValue;
END_RCPP
}
// dilate_cpp
IntegerMatrix dilate_cpp(IntegerMatrix segim, IntegerMatrix kern);
RcppExport SEXP _ProFound_dilate_cpp(SEXP segimSEXP, SEXP kernSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type segim(segimSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type kern(kernSEXP);
    rcpp_result_gen = Rcpp::wrap(dilate_cpp(segim, kern));
    return rcpp_result_gen;
END_RCPP
}
// point_in_polygon
LogicalVector point_in_polygon(NumericVector x, NumericVector y, NumericVector poly_x, NumericVector poly_y);
RcppExport SEXP _ProFound_point_in_polygon(SEXP xSEXP, SEXP ySEXP, SEXP poly_xSEXP, SEXP poly_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_x(poly_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_y(poly_ySEXP);
    rcpp_result_gen = Rcpp::wrap(point_in_polygon(x, y, poly_x, poly_y));
    return rcpp_result_gen;
END_RCPP
}
// Cadacs_MakeSkyGrid
void Cadacs_MakeSkyGrid(Rcpp::NumericMatrix image, Rcpp::NumericMatrix sky, Rcpp::NumericMatrix skyRMS, Rcpp::Nullable<Rcpp::IntegerMatrix> objects, Rcpp::Nullable<Rcpp::IntegerMatrix> mask, const int box1, const int box2, const int grid1, const int grid2, const int boxadd1, const int boxadd2, const int type, const int skypixmin, const int boxiters, const int doclip, const int skytype, const int skyRMStype, const double sigmasel);
RcppExport SEXP _ProFound_Cadacs_MakeSkyGrid(SEXP imageSEXP, SEXP skySEXP, SEXP skyRMSSEXP, SEXP objectsSEXP, SEXP maskSEXP, SEXP box1SEXP, SEXP box2SEXP, SEXP grid1SEXP, SEXP grid2SEXP, SEXP boxadd1SEXP, SEXP boxadd2SEXP, SEXP typeSEXP, SEXP skypixminSEXP, SEXP boxitersSEXP, SEXP doclipSEXP, SEXP skytypeSEXP, SEXP skyRMStypeSEXP, SEXP sigmaselSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type image(imageSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sky(skySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type skyRMS(skyRMSSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerMatrix> >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerMatrix> >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< const int >::type box1(box1SEXP);
    Rcpp::traits::input_parameter< const int >::type box2(box2SEXP);
    Rcpp::traits::input_parameter< const int >::type grid1(grid1SEXP);
    Rcpp::traits::input_parameter< const int >::type grid2(grid2SEXP);
    Rcpp::traits::input_parameter< const int >::type boxadd1(boxadd1SEXP);
    Rcpp::traits::input_parameter< const int >::type boxadd2(boxadd2SEXP);
    Rcpp::traits::input_parameter< const int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const int >::type skypixmin(skypixminSEXP);
    Rcpp::traits::input_parameter< const int >::type boxiters(boxitersSEXP);
    Rcpp::traits::input_parameter< const int >::type doclip(doclipSEXP);
    Rcpp::traits::input_parameter< const int >::type skytype(skytypeSEXP);
    Rcpp::traits::input_parameter< const int >::type skyRMStype(skyRMStypeSEXP);
    Rcpp::traits::input_parameter< const double >::type sigmasel(sigmaselSEXP);
    Cadacs_MakeSkyGrid(image, sky, skyRMS, objects, mask, box1, box2, grid1, grid2, boxadd1, boxadd2, type, skypixmin, boxiters, doclip, skytype, skyRMStype, sigmasel);
    return R_NilValue;
END_RCPP
}
// water_cpp
Rcpp::IntegerMatrix water_cpp(Rcpp::NumericVector image, const int nx, const int ny, const double abstol, const double reltol, const double cliptol, const int ext, const double skycut, const int pixcut, const bool verbose, const int Ncheck);
RcppExport SEXP _ProFound_water_cpp(SEXP imageSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP abstolSEXP, SEXP reltolSEXP, SEXP cliptolSEXP, SEXP extSEXP, SEXP skycutSEXP, SEXP pixcutSEXP, SEXP verboseSEXP, SEXP NcheckSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type cliptol(cliptolSEXP);
    Rcpp::traits::input_parameter< const int >::type ext(extSEXP);
    Rcpp::traits::input_parameter< const double >::type skycut(skycutSEXP);
    Rcpp::traits::input_parameter< const int >::type pixcut(pixcutSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const int >::type Ncheck(NcheckSEXP);
    rcpp_result_gen = Rcpp::wrap(water_cpp(image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck));
    return rcpp_result_gen;
END_RCPP
}
// addmat
NumericMatrix addmat(NumericMatrix base, NumericMatrix add, IntegerVector xlim, IntegerVector ylim);
RcppExport SEXP _ProFound_addmat(SEXP baseSEXP, SEXP addSEXP, SEXP xlimSEXP, SEXP ylimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type base(baseSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type add(addSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type xlim(xlimSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ylim(ylimSEXP);
    rcpp_result_gen = Rcpp::wrap(addmat(base, add, xlim, ylim));
    return rcpp_result_gen;
END_RCPP
}
// order_cpp
IntegerVector order_cpp(NumericVector x);
RcppExport SEXP _ProFound_order_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(order_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// tabulate_cpp
IntegerVector tabulate_cpp(const IntegerVector& x, const int max);
RcppExport SEXP _ProFound_tabulate_cpp(SEXP xSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(tabulate_cpp(x, max));
    return rcpp_result_gen;
END_RCPP
}
// water_cpp_old
IntegerVector water_cpp_old(const NumericVector image, const int nx, const int ny, const double abstol, const double reltol, const double cliptol, const int ext, const double skycut, const int pixcut, const bool verbose, const int Ncheck);
RcppExport SEXP _ProFound_water_cpp_old(SEXP imageSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP abstolSEXP, SEXP reltolSEXP, SEXP cliptolSEXP, SEXP extSEXP, SEXP skycutSEXP, SEXP pixcutSEXP, SEXP verboseSEXP, SEXP NcheckSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type cliptol(cliptolSEXP);
    Rcpp::traits::input_parameter< const int >::type ext(extSEXP);
    Rcpp::traits::input_parameter< const double >::type skycut(skycutSEXP);
    Rcpp::traits::input_parameter< const int >::type pixcut(pixcutSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const int >::type Ncheck(NcheckSEXP);
    rcpp_result_gen = Rcpp::wrap(water_cpp_old(image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ProFound_interpolateAkimaGrid", (DL_FUNC) &_ProFound_interpolateAkimaGrid, 4},
    {"_ProFound_interpolateLinearGrid", (DL_FUNC) &_ProFound_interpolateLinearGrid, 4},
    {"_ProFound_dilate_cpp", (DL_FUNC) &_ProFound_dilate_cpp, 2},
    {"_ProFound_point_in_polygon", (DL_FUNC) &_ProFound_point_in_polygon, 4},
    {"_ProFound_Cadacs_MakeSkyGrid", (DL_FUNC) &_ProFound_Cadacs_MakeSkyGrid, 18},
    {"_ProFound_water_cpp", (DL_FUNC) &_ProFound_water_cpp, 11},
    {"_ProFound_addmat", (DL_FUNC) &_ProFound_addmat, 4},
    {"_ProFound_order_cpp", (DL_FUNC) &_ProFound_order_cpp, 1},
    {"_ProFound_tabulate_cpp", (DL_FUNC) &_ProFound_tabulate_cpp, 2},
    {"_ProFound_water_cpp_old", (DL_FUNC) &_ProFound_water_cpp_old, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProFound(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
