# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolates a grid of equally spaced values
#'
#' @param x X coordinates of pixels in grid
#' @param y Y coordinates of pixels in grid
#' @param grid Input matrix with values to be interpolated
#' @param output Output matrix. It starts at the origin on both dimensions, and
#'   its interpolated values are calculated on the centre of each cell
.interpolateAkimaGrid <- function(x, y, grid, output) {
    invisible(.Call(`_ProFound_interpolateAkimaGrid`, x, y, grid, output))
}

.interpolateLinearGrid <- function(xseq, yseq, tempmat_sky, output) {
    invisible(.Call(`_ProFound_interpolateLinearGrid`, xseq, yseq, tempmat_sky, output))
}

profoundAperCover <- function(x, y, cx, cy, rad, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundAperCover`, x, y, cx, cy, rad, depth, nthreads)
}

profoundAperWeight <- function(cx, cy, rad, dimx = 100L, dimy = 100L, wt = as.numeric( c(1)), rad_pow = 0, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundAperWeight`, cx, cy, rad, dimx, dimy, wt, rad_pow, depth, nthreads)
}

profoundAperFlux <- function(image, cx, cy, rad, wt = as.numeric( c(1)), rad_pow = 0, deblend = FALSE, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundAperFlux`, image, cx, cy, rad, wt, rad_pow, deblend, depth, nthreads)
}

.dilate_cpp <- function(segim, kern, expand = 0L, nthreads = 1L) {
    .Call(`_ProFound_dilate_cpp`, segim, kern, expand, nthreads)
}

profoundEllipCover <- function(x, y, cx, cy, rad, ang = 0, axrat = 1, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundEllipCover`, x, y, cx, cy, rad, ang, axrat, depth, nthreads)
}

profoundEllipWeight <- function(cx, cy, rad, ang = as.numeric( c(0)), axrat = as.numeric( c(1)), dimx = 100L, dimy = 100L, wt = as.numeric( c(1)), rad_pow = 0, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundEllipWeight`, cx, cy, rad, ang, axrat, dimx, dimy, wt, rad_pow, depth, nthreads)
}

profoundEllipFlux <- function(image, cx, cy, rad, ang = as.numeric( c(0)), axrat = as.numeric( c(1)), wt = as.numeric( c(1)), rad_pow = 0, deblend = FALSE, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundEllipFlux`, image, cx, cy, rad, ang, axrat, wt, rad_pow, deblend, depth, nthreads)
}

profoundPolyCover <- function(x, y, poly_x, poly_y, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundPolyCover`, x, y, poly_x, poly_y, depth, nthreads)
}

profoundPolyFlux <- function(image, poly_x, poly_y, depth = 3L, nthreads = 1L) {
    .Call(`_ProFound_profoundPolyFlux`, image, poly_x, poly_y, depth, nthreads)
}

.Cadacs_MakeSkyGrid <- function(image, sky, skyRMS, objects = NULL, mask = NULL, box1 = 100L, box2 = 100L, grid1 = 100L, grid2 = 100L, boxadd1 = 50L, boxadd2 = 50L, type = 2L, skypixmin = 5000L, boxiters = 0L, doclip = 1L, skytype = 1L, skyRMStype = 2L, sigmasel = 1, nthreads = 1L) {
    invisible(.Call(`_ProFound_Cadacs_MakeSkyGrid`, image, sky, skyRMS, objects, mask, box1, box2, grid1, grid2, boxadd1, boxadd2, type, skypixmin, boxiters, doclip, skytype, skyRMStype, sigmasel, nthreads))
}

profoundSegimFlux <- function(image, segim, nthreads = 1L) {
    .Call(`_ProFound_profoundSegimFlux`, image, segim, nthreads)
}

.vec_this_in_vec_that <- function(vec_this, vec_that, invert = FALSE, nthreads = 1L) {
    .Call(`_ProFound_vec_this_in_vec_that`, vec_this, vec_that, invert, nthreads)
}

.mat_this_in_vec_that <- function(mat_this, vec_that, invert = FALSE, nthreads = 1L) {
    .Call(`_ProFound_mat_this_in_vec_that`, mat_this, vec_that, invert, nthreads)
}

water_cpp <- function(image = 0L, nx = 1L, ny = 1L, abstol = 1, reltol = 0, cliptol = 1000000, ext = 1L, skycut = 0, pixcut = 1L, verbose = FALSE, Ncheck = 1000000L, nthreads = 1L) {
    .Call(`_ProFound_water_cpp`, image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck, nthreads)
}

.addmat_cpp <- function(base, add, xlim, ylim) {
    .Call(`_ProFound_addmat`, base, add, xlim, ylim)
}

.order_cpp <- function(x) {
    .Call(`_ProFound_order_cpp`, x)
}

.tabulate_cpp <- function(x, max) {
    .Call(`_ProFound_tabulate_cpp`, x, max)
}

water_cpp_old <- function(image = 0L, nx = 1L, ny = 1L, abstol = 1, reltol = 0, cliptol = 1000000, ext = 1L, skycut = 0, pixcut = 1L, verbose = FALSE, Ncheck = 1000000L) {
    .Call(`_ProFound_water_cpp_old`, image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck)
}

