# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolates a grid of equally spaced values
#'
#' @param x X coordinates of pixels in grid
#' @param y Y coordinates of pixels in grid
#' @param grid Input matrix with values to be interpolated
#' @param output Output matrix. It starts at the origin on both dimensions, and
#'   its interpolated values are calculated on the centre of each cell
.interpolateAkimaGrid <- function(x, y, grid, output) {
    invisible(.Call(`_ProFound_interpolateAkimaGrid`, x, y, grid, output))
}

.interpolateLinearGrid <- function(xseq, yseq, tempmat_sky, output) {
    invisible(.Call(`_ProFound_interpolateLinearGrid`, xseq, yseq, tempmat_sky, output))
}

profoundAperCover <- function(x, y, cx, cy, rad, depth = 4L) {
    .Call(`_ProFound_profoundAperCover`, x, y, cx, cy, rad, depth)
}

.dilate_cpp <- function(segim, kern, expand = 0L) {
    .Call(`_ProFound_dilate_cpp`, segim, kern, expand)
}

profoundEllipCover <- function(x, y, cx, cy, rad, ang, axrat, depth = 4L) {
    .Call(`_ProFound_profoundEllipCover`, x, y, cx, cy, rad, ang, axrat, depth)
}

.point_in_polygon_cpp_short <- function(testx, testy, vertx, verty) {
    .Call(`_ProFound_pnpoly`, testx, testy, vertx, verty)
}

.Cadacs_MakeSkyGrid <- function(image, sky, skyRMS, objects = NULL, mask = NULL, box1 = 100L, box2 = 100L, grid1 = 100L, grid2 = 100L, boxadd1 = 50L, boxadd2 = 50L, type = 2L, skypixmin = 5000L, boxiters = 0L, doclip = 1L, skytype = 1L, skyRMStype = 2L, sigmasel = 1) {
    invisible(.Call(`_ProFound_Cadacs_MakeSkyGrid`, image, sky, skyRMS, objects, mask, box1, box2, grid1, grid2, boxadd1, boxadd2, type, skypixmin, boxiters, doclip, skytype, skyRMStype, sigmasel))
}

water_cpp <- function(image = 0L, nx = 1L, ny = 1L, abstol = 1, reltol = 0, cliptol = 1000000, ext = 1L, skycut = 0, pixcut = 1L, verbose = FALSE, Ncheck = 1000000L) {
    .Call(`_ProFound_water_cpp`, image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck)
}

.addmat_cpp <- function(base, add, xlim, ylim) {
    .Call(`_ProFound_addmat`, base, add, xlim, ylim)
}

.order_cpp <- function(x) {
    .Call(`_ProFound_order_cpp`, x)
}

.tabulate_cpp <- function(x, max) {
    .Call(`_ProFound_tabulate_cpp`, x, max)
}

water_cpp_old <- function(image = 0L, nx = 1L, ny = 1L, abstol = 1, reltol = 0, cliptol = 1000000, ext = 1L, skycut = 0, pixcut = 1L, verbose = FALSE, Ncheck = 1000000L) {
    .Call(`_ProFound_water_cpp_old`, image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck)
}

